name: sohba
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  cloud_firestore: ^4.17.5
  cloudinary_public: ^0.23.1
  cupertino_icons: ^1.0.6
  firebase_auth: ^4.20.0
  firebase_core: ^2.31.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  flutter_screenutil: ^5.9.0
  gap: ^3.0.1
  get_it: ^7.7.0
  google_fonts: null
  hive_flutter: ^1.1.0
  http: ^1.2.1
  image_picker: ^1.0.8
  laravel_exception: ^0.0.4
  local_auth: ^2.1.8
  shared_preferences: ^2.2.3
  stylish_bottom_bar: ^1.1.0

dev_dependencies:
  build_runner: ^2.1.4
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
