name: sohba
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  cloud_firestore: ^4.17.5
  cupertino_icons: ^1.0.6
  firebase_auth: ^4.20.0
  firebase_core: ^2.31.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  flutter_screenutil: ^5.9.0
  gap: ^3.0.1
  get_it: ^7.7.0
  google_fonts: null
  image_picker: ^1.0.8
  laravel_exception: ^0.0.4
  local_auth: ^2.1.8
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
